### ISSUE TITLE
Searching for anything expands all tabs

### ISSUE THREAD

**Issue by aiolos01** [gerwaric/acquisition#46] opened 2024-07-22 10:24 UTC
The search crashes seem to be fixed. At least I haven't encountered any yet. I might actually play this league so I guess I'll test it some more.

There's a new bug however.  As the title says, type "a" in the search bar and see that everything expands (correctly). Then delete the "a" and everything remains expanded. Type "aaa" (which doesn't exist) and then delete it all at once. Now everything has contracted.

Not a big issue (there's always the workaround I described to contract everything) but when you have time, take a look.

**Comment by gerwaric** [comment] 2024-07-22 14:53
I was able to replicate and correct this behavior:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.1-alpha.10

**Comment by gerwaric** [comment] 2024-07-25 04:51
I'm closing this for now, since I think the issue is fixed. Let me know if it happens again.

**Closed by gerwaric** 2024-07-25 04:51 UTC
Labels: bug
