### ISSUE TITLE
Prices lost when upgrading to 0.11.7 from 0.11.5

### ISSUE THREAD

**Issue by s-vourakis** [gerwaric/acquisition#78] opened 2024-11-20 19:30 UTC
I have a lot of old tabs on standard. I upgraded to 0.11.7 today and when I run acquisition I got no tabs or characters listed. I refreshed all and now all tabs ans characters are listed correctly but almost all prices have been lost. The prices I have set in premium stash tabs are there and (oddly enough) some of the "acquisition prices" are still there (2 tabs out of 30-40 and not even all items) but the majority have been lost. 

It's kind of a strange behavior to keep a few of the old prices. I would expect it would either keep all or none.

Is there any way to recover them. There are a lot of tabs and there's no way I'd reprice all of them.

**Comment by gerwaric** [comment] 2024-11-20 19:46
Acquisition should have made a copy of your data files when you first ran the new version--so at least the data shouldn't be lost as long as a copy of that backup folder and its contents exist.

However, since I'm not sure what happened yet, I don't know what I'll need to change to make them work again.

I'll think about the best way to troubleshoot this and get back to you later today, probably with some questions.

**Comment by gerwaric** [comment] 2024-11-20 21:03
@s-vourakis Bad news--I can't find any changes since 0.5 that would have led to prices dissapearing.

I have a couple of theories, but no easy way to test them.

Would you be comfortable sharing data files with stash tab contents with me?  The two files I'm thinking of do not contain any login information or credentials, but they would help me quickly test some of my theories. If you are ok with this, I'll help you get those files to me. If you are not comfortable sharing your data--no problem--I'll find another way to troubleshoot this issue.

**Comment by s-vourakis** [comment] 2024-11-20 23:25
The new versions make a backup of the data folder however the latest backup I have is 11.3 from September when I installed 11.5. It seems 11.7 didn't make a backup. 

I reinstalled 11,5 and restored the 11.3 backup. No items listed. I tried to update all tabs and got "QNetworkReply::ContentAccessDenied". Seems 11.5 can't connect any more. You already mention this in the change log, just confirming it. It should however list all my items from the cache without needing to refresh them but it didn't. I even restored the entire acquisition folder (username/appdata/local/acquisition) from yesterday's drive backup but it didn't change anything.

**Comment by gerwaric** [comment] 2024-11-20 23:52
I have data files saved from 0.11.3 as well.  I'll look into my own files and see if I can see anything that has changed. Once I know more I will report back.

**Comment by gerwaric** [comment] 2024-11-21 00:14
I just realized one issue. The new account system caused a problem with the names of the data files.

I have an idea for a quick fix. However, this fix will also cause problems with data files depending on how people use the new account system. There may be other problems causing prices to disappear, too, but I will make a release for this one first and explain how to avoid the problem caused by the workaround. One step at a time.

The correct answer is to restructure how acquisition stores data, but that's not an easy fix.

**Comment by gerwaric** [comment] 2024-11-21 03:58
I've attempted to fix this issue with this release:
https://github.com/gerwaric/acquisition/releases/tag/v0.11.8

You will have to do some manually copying and pasting to restore your data files from 0.11.3, so I added instructions to the release. Let me know if they don't work for you, or if they are unclear.

**Comment by s-vourakis** [comment] 2024-11-21 20:38
The .exe on your latest version says 0.11.7. I downloaded it anyway, installed it, copied the 11.3 backup which is the latest I have and then run it. It didn't load anything from the cache. I refreshed all, waited 2 hours for the refresh to finish and after it did I got exactly the same result as yesterday. Most prices are lost with the odd exception of 2 tabs that still have some.
Are you sure this is the 11.8 version? All the other links (except the .exe) say 11.8)

**Comment by gerwaric** [comment] 2024-11-21 21:09
You're right, it's not the 0.11.8 installer. I'm trying to fix that now.

**Comment by gerwaric** [comment] 2024-11-21 21:38
@s-vourakis I think I've fixed it. I'm not sure what went wrong, but this is just another reason I need to learn proper CI/CD to automate this kind of stuff.

**Comment by s-vourakis** [comment] 2024-11-22 09:56
This fixes the issue. The prices are back from the 11.3 backup. It loaded the prices from the cache, I then refreshed all tabs and the prices are still there along with the premium tab prices I have recently set. Thank you.

Just to mention that neither 11.7 not 11.8 made backups of the old data folder. I believe you disabled it at some point?

**Comment by gerwaric** [comment] 2024-11-23 01:02
I'm glad this fixes the issue of the dissappearing prices, so I'm closing this issue.

I'm still not sure why it didn't make a backup. That  code hasn't been touched in a while.

**Closed by gerwaric** 2024-11-23 01:02 UTC
Labels: bug
